<?php
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
/** @noinspection PhpIncludeInspection */
//To Solve File REST_Controller not found
require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
require APPPATH . 'libraries/ImplementJWT.php';

/**
 * This is an example of a few basic user interaction methods you could use
 * all done with a hardcoded array
 *
 * @package         CodeIgniter
 * @subpackage      Rest Server
 * @category        Controller
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver

 */
class Users extends REST_Controller {

    function __construct()
    {
        // Construct the parent class
        parent::__construct();
        header("Access-Control-Allow-Origin:*");
        header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
        header('Access-Control-Request-Method: OPTIONS, POST, GET, PUT, DELETE');

        // Configure limits on our controller methods
        // Ensure you have created the 'limits' table and enabled 'limits' within application/config/rest.php
        $this->methods['users_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['users_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['users_delete']['limit'] = 50; // 50 requests per hour per user/key

        $this->objOfJwt = new ImplementJWT();
    }

    public function users_get()
    {
       
    }

    public function users_post()
    {
        // $this->some_model->update_user( ... );
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }

    public function users_delete()
    {
        $id = (int) $this->get('id');

        // Validate the id.
        if ($id <= 0)
        {
            // Set the response and exit
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        // $this->some_model->delete_something($id);
        $message = [
            'id' => $id,
            'message' => 'Deleted the resource'
        ];

        $this->set_response($message, REST_Controller::HTTP_NO_CONTENT); // NO_CONTENT (204) being the HTTP response code
    }
    public function login_post(){
        $credentials = array(
            'username' =>  $this->post('username'),  // Which is School ID btw
            'password' => $this->post('password')
        );
        $result = $this->user->login($credentials);

        if ($result[0]){
            $session = array (
                'id' => $result[1]->user_school_id,
                'type' => $result[1]->user_type,
                'college' => $result[2]->ui_college,
                'department' => $result[2]->ui_dept,
                'position'=> $result[2]->ui_position 
            );
            $this->session->set_userdata($session);
            // $tokenData['id'] = $result[1]->user_school_id;
            // $tokenData['type'] = $result[1]->user_type;
            $jwtToken = $this->objOfJwt->GenerateToken($session);
            $result[3] = $jwtToken;

            // $this->session->sess_destroy();

            // var_dump($_SESSION);
        }

        // var_dump($_SESSION);
        $this->response($result);
    }
    
    public function registration_get(){
        // For checking if the user exists
    }
    public function register_post(){
        // For registering new users
        // var_dump($this-  >post());
        $info = array (
            'ui_school_id' => $this->post('id'),
            'ui_college' => $this->post('college'),
            'ui_dept' => $this->post('dept'),
            'ui_email' => $this->post('email'),
            'ui_position' => $this->post('position'),
            'ui_Fname'=> $this->post('fName'),
            'ui_Mname'=> $this->post('mName'),
            'ui_Lname'=> $this->post('lName'),
            'ui_gender'=> $this->post('gender'),
            //'ui_age'=> $this->post(''),
            'ui_contact_number'=> $this->post('cNumber'),
            'ui_birthday' => $this->post('bDay')
        );

        $cred = array (
            'user_school_id' => $this->post('id'),
            'user_pass' => $this->post('pass'),
            'user_type' => $this->post('type'),
        );



        $result = $this->user->register($info,$cred);
        $this->response($result);
        
    }
    public function getall_get(){
        $result = $this->user->get_allusers();
        $this->response($result);
    }

    public function check_login_post(){
        $response = [];
        // var_dump($this->post('token'));
        $jwtData = $this->objOfJwt->DecodeToken($this->post('token'));
        // var_dump($jwtData['id']);
        $result = $this->user->check($jwtData['id']);
        // var_dump($result);
        if($result){
            $response[0] = true;
            $response[1] = $jwtData['type'];
        }
        // var_dump($response);
        $this->response($response);
        // $this->response($jwtData);
    }

    public function submit_proposal_post(){
        $response = [];
        // $props = $this->admin->get_all_proposals();
        // foreach ($row => $props) {
        //     if ($row->proposal_title === $this->post('title')){
        //         $response[0] = 'repeat';
        //     }
        // }
        // var_dump($this->post());
        $jwtData = $this->objOfJwt->DecodeToken($this->post('token'));

        // var_dump($_FILES);
        // $date_s = split('-', $this->post('date_start'),2);
        // $date_e = split('-', $this->post('date_end'),2);
        // $date_s = "";
        // $date_e = "";
        // for ($i=0; $i < 10 ; $i++) { 
        //     if($i == 9){
        //         $date_s .= $this->post('date_start')[$i]+1;
        //         $date_e .= $this->post('date_end')[$i]+1;            
        //     }else{
        //         $date_s .= $this->post('date_start')[$i];
        //         $date_e .= $this->post('date_end')[$i];
        //     }


        // }
        // var_dump($_FILES);
        // var_dump($this->post());
        $proposal_details = array(
            'user_id' => $jwtData['id'],
            'proposal_title' => $this->post('title'),        
            'proposal_beneficiaries' => $this->post('b_target'),        
            'proposal_bene_gender' => $this->post('b_gender'),        
            'proposal_date_start' =>$this->post('date_start'),        
            'proposal_date_end' => $this->post('date_end'),        
            'proposal_venue' => $this->post('venue'),
            'proposal_directory' => '../../../assets/uploaded_files/'.$jwtData['college'].'/'.$jwtData['department'].'/'.$this->post('title').'/'.$this->post('fileName'),
            'type_id' => $this->post('trans_type'),
            'proposal_partner'=> $this->post('partner'),
            'proponents'=> $this->post('proponents'),
            'accreditation_level'=> $this->post('accre_level'),
            'total_hours'=> $this->post('total_hours'),
            'budget_ustp'=> $this->post('budget_ustp'),
            'budget_partner'=> $this->post('budget_partner')        
        );

        $result = $this->user->submit_proposal($proposal_details);
        // $response[1] = $result;
        $this->response($result);
        // $this->response(true);

    }
        
        public function getNotifs_post(){
        $result = $this->user->get_notifs($this->post('id'));

        $this->response($result);
    }



    public function file_upload_post(){
        // var_dump($_POST);
        // var_dump($_FILES);
        $data = array(
            'id' => $this->post('id'),
            'file_type' => $this->post('file_type'),
            'folder' => $this->post('folder')
        );

        $result = $this->user->upload_file($data);
        // $data = json_decode(file_get_contents('php://input'), true);
        // var_dump($data);
        // $rest_json = file_get_contents("php://input");
        // var_dump($rest_json);
        // $_FILE = json_decode($rest_json, true);
        // echo json_encode($_POST);
        $this->response($result);
    }



    ////Admin Fucntions

    public function get_des_proposals_get(){
        $result = $this->admin->get_des_proposals();

        $this->response($result);
    }
    public function get_proposals_get(){
        $result = $this->admin->get_proposals();

        $this->response($result);
    }

    public function get_proposal_post(){
        $id = $this->post('id');
        $result = $this->admin->get_proposal($id);
        $this->response($result);
    }

    public function get_events_get(){
        $result = $this->admin->get_events();
        $this->response($result);
    }

    public function proposal_approval_post(){
        // var_dump($this->post());
        $approval = array (
            'id' => $this->post('id'),
            'status' => $this->post('decision'),
            'title' => $this->post('title')
        );
        $result = $this->admin->proposal_approval($approval);

        $this->response($result);
    }





    public function get_transactions_post(){
        $result = $this->user->get_transactions($this->post('id'));

        $this->response($result);
    }

    public function get_prexc_post(){
        $result = $this->admin->get_prexc($this->post('quarter'));
        $this->response($result);

    }
    public function get_hemis_post(){
        $result = $this->admin->get_hemis($this->post('quarter'));
        $this->response($result);

    }

    public function get_unregistered_get(){
        $result = $this->admin->get_unregistered();
        $this->response($result);
    }

    public function approve_registration_post(){
        $data = array(
            'id' => $this->post('id'),
            'status' => $this->post('status')
        );

        $result = $this->admin->approve_registration($data);

        $this->response($result);
    }

    public function update_project_status_post(){
        $data = array(
            'id' => $this->post('id'),
            'status' => $this->post('status')
        );
        $result = $this->admin->update_project_status($data);

        $this->response($result);
    }

    public function moa_c_upload_post(){
        var_dump($_FILES);
        $data = array(
            'id' => $this->post('id'),
            'folder' => $this->post('folder'),
            'prop_id' => $this->post('prop_id'),
            'user_id' => $this->post('user_id'),
        );
        $result = $this->admin->moa_c_upload($data);
        $this->response($result);
    }
    // public function logout(){
    //     $this->session->session_destroy();
    //     return true;
    // }

}
